language: ruby
before_script:
  - bundle exec sidekiq -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log &
  - sleep 1
script: rspec spec
bundler_args: --without=extras
services:
  - redis-server
rvm:
  - '2.4.0'
  - jruby-9.1.6.0
